;==============================================================================
; Name:         Atari 2600 standard include files.
; Filename:     atari2k6.inc
; Platform:     Atari 2600
; Language:		6507 Assembly Language (https://www.cc65.org/doc/ca65.html)
; Author:       Justin Lane (atari2600@jigglesoft.co.uk)
; Date:         2019-01-28 19:35
; Vesion:		1.1.0
;------------------------------------------------------------------------------
; Licence:		This file is licensed under the following licence:-
;				 		CC Attribution 3.0 Unported
;						http://creativecommons.org/licenses/by/3.0/
;------------------------------------------------------------------------------


;==============================================================================
; Atari 2600 Standard Includes.
;==============================================================================

				; Atari 2600 standard include file.
				.INCLUDE		"a2k6std.inc"

				; Atari 2600 standard extra include file.
				.INCLUDE		"a2k6stdx.inc"

;------------------------------------------------------------------------------


