;==============================================================================
; Name:         Atari 2600 standard include files.
; Filename:     atari2k6.inc
; Platform:     Atari 2600
; Language:		6507 Assembly Language (https://www.cc65.org/doc/ca65.html)
; Author:       Justin Lane (atari2600@jigglesoft.co.uk)
; Date:         2019-02-18 21:44
; Vesion:		1.1.2
;------------------------------------------------------------------------------
; Licence:		This file is licensed under the following licence:-
;						Creative Commons Attribution 4.0 International
;						http://creativecommons.org/licenses/by/4.0/
;						with an exception, see /LICENCE.txt file.
;------------------------------------------------------------------------------


;==============================================================================
; Atari 2600 Standard Includes.
;==============================================================================

				; Atari 2600 standard include file.
				.INCLUDE		"a2k6std.inc"

				; Atari 2600 standard extra include file.
				.INCLUDE		"a2k6stdx.inc"

;------------------------------------------------------------------------------


